### ISSUE TITLE
`struct()` doesn't accept keys with characters such as `.` and `-`

### ISSUE THREAD

**Issue by keith** [bazelbuild/starlark#103]
When trying to create a [`struct`](https://docs.bazel.build/versions/master/skylark/lib/struct.html#struct), doing so with keys containing some non alpha numeric characters doesn't work directly, but does work if you use a dictionary for indirection:

```bzl
# Normal case
print(struct(foo = 1))
# None of these work
print(struct("foo.bar" = 1))
print(struct("foo-bar" = 1))
print(struct(foo.bar = 1))
print(struct(foo-bar = 1))
# It works if you use a dictionary
dictionary = {"foo.bar": 1, "foo-bar": 2}
print(struct(**dictionary))
```

This workaround is fine but it might be nice for the other examples to work as well.

**Comment by stepancheg** [comment]
`struct` is a regular function, like `dict`. Try the same with `dict` function or any other user-defined function like `def foo(**kwargs): print(kwargs)`.

Starlark could explicitly check that vararg map keys are valid identifiers. But I guess that would be expensive.

Python does not validate kwargs keys either.

Note, `struct` function is not a part of Starlark spec (and this repo is about Starlark spec).

**Comment by alandonovan** [comment]
I agree with Stepan. Struct imposes no restriction on its field names, but only identifiers can be set and retrieved using the basic syntax. This is indeed what Python does.

struct isn't in the spec, but clearly there's a need for something like it. Although It's trivial for users to roll their own, there are a great variety of valid designs: read-only vs updatable; a single type vs a family of distinct constructors (like bazel providers); schemaful vs schemaless [schema = set of permitted fields]; sparse vs dense representation; and so on.

**Comment by keith** [comment]
Thanks for the context
