### ISSUE TITLE
Concatenation of dict select expressions

### ISSUE THREAD

**Issue by sitaktif** [bazelbuild/starlark#114]
Starlark allows the concatenation of `select` statements that return lists, such as:

```python
my_binary(
  name = "greatbin",
  deps = ["some", "deps"]
    + select({"//:special_cpu": ["//some:target_for_special_cpu"], "//conditions:default": []})
    + select({"//:special_os": ["//some:target_for_special_os"], "//conditions:default": []})
)
```

This is very handy when generating code, which commonly happens when writing bazel rules.

Unfortunately, one cannot concatenate selects that return dicts:

```python
my_rule(
  name = "greatbin",
  extra_env = {"FROB_PATH": "somepath"}
    + select({"//:special_cpu": {"SPECIAL_CPUFLAGS": "myspecialcpu"}, "//conditions:default": {}})
    + select({"//:special_os": {"SPECIAL_OSFLAGS": "myspecialos"}, "//conditions:default": {}})
    + select({"//:debug_mode": {"DEBUG": "true"}, "//conditions:default": {}})
    + ...
)
```

as this results in the following error: `type 'dict(label, string)' doesn't support select concatenation`.

This error is hit both when concatenating a `dict` and a `select()`, and when concatenating two `select()`s.

Related to #14.

**Comment by alandonovan** [comment]
`select` is a feature of the Build Language, Bazel's dialect of Starlark, rather than the core Starlark language itself.

Could you file this issue in bazelbuild/bazel? Thanks.

**Comment by alandonovan** [comment]
There's no reason why I can't file it myself. Done: https://github.com/bazelbuild/bazel/issues/12457

**Comment by sitaktif** [comment]
Thanks @alandonovan 🙏
