### ISSUE TITLE
Question: Possibility of `find` for list.

### ISSUE THREAD

**Issue by Mythra** [bazelbuild/starlark#121]
Looking through the [documentation for list on bazel's doc site](https://docs.bazel.build/versions/master/skylark/lib/list.html#index). It appears there isn't a method to check if a list "contains" an element. The only "get"-esque method: `index()` throws an error if the element does not exist.

This differs then other containers like dict, which contains: `dict.get(key, default=None)` which allows returning a "None" value.
The String type which also supports `.index()` which throws an error offers a find method: <https://docs.bazel.build/versions/master/skylark/lib/string.html#find> which returns a -1 if the element doesn't exist.

I'm currently working on a list being generated in a repository rule, that gets put into a bazel file, and bazel throws a fit from the generated list:

```
ERROR: <snipped>/BUILD.bazel:10:10: Label '//pkg/auth:go_library' is duplicated in the 'deps' attribute of rule 'authentication.go.deps'
```

Now there are multiple ways I'm working on fixing this that should avoid the duplicate altogether, and I can add a `find()` method myself similar to the String type. However, it'd be nice if it were just in the standard library.

**Comment by laszlocsomor** [comment]
The `in` operator can do this:

```
if x in elements:
```

Demo:

```
  $ cat BUILD
load("foo.bzl", "foo")

foo("a", ["a", "b"])

foo("b", ["c", "d"])
```

```
  $ cat foo.bzl 
def foo(x, xs):
    if x in xs:
        native.filegroup(name = x)
```

```
  $ bazel query //:*
//:a
//:BUILD
Loading: 1 packages loaded
```
