### ISSUE TITLE
spec: mistake regarding sign of x % y

### ISSUE THREAD

**Issue by alandonovan** [bazelbuild/starlark#148]
The spec currently says

> The // and % operations on integers compute floored division and remainder of floored division, respectively. If the signs of the operands differ, the sign of the remainder x % y matches that of the dividend, x.

yet the Go and Java implementations currently exhibit this behavior, as does Python[23]:

```
Welcome to Starlark (java.starlark.net)
>> maxlong = 0x7fffffffffffffff
>> minlong = -maxlong-1
>> 1 % minlong
-9223372036854775807
```

What's more, Python's language reference, which we have aimed to follow here, says:

https://docs.python.org/3/reference/expressions.html#binary-arithmetic-operations
> The modulo operator always yields a result with the same sign as its second operand (or zero); 

I think the text of our spec is wrong, and should be made to match Python. The implementations may have incorporated the mistake into their behavior, and will need auditing. D'oh.

(Context: https://github.com/bazelbuild/bazel/pull/12667)

@stepancheg

**Comment by brandjon** [comment]
Yep, all the wording I'm familiar with is that it gets the sign of the right-hand operand. You want the property that the result repeats periodically in the same way, even when x is at or about 0.
