### ISSUE TITLE
repr of OutputGroupInfo is confusing

### ISSUE THREAD

**Issue by sfreilich** [bazelbuild/starlark#149]
The repr of `target[OutputGroupInfo]` is:

```bzl
struct(_hidden_top_level_INTERNAL_ = depset([]))
```

That probably should have a `repr` that mentions `OutputGroupInfo` and hides the field for `OutputGroupInfo.HIDDEN_TOP_LEVEL`.

**Comment by alandonovan** [comment]
I don't really understand what _hidden_top_level_INTERNAL_ is, but judging from the number and variety of references to it in our corpus, it appears to be neither hidden nor INTERNAL.

This bug should be reported at bazelbuild/bazel. This repo is for issues related to the core Starlark language, not Bazel's Starlark API.

**Comment by alandonovan** [comment]
See https://github.com/bazelbuild/bazel/issues/12682
