### ISSUE TITLE
Lexing issue on 01

### ISSUE THREAD

**Issue by ndmitchell** [bazelbuild/starlark#162]
From reading the spec, as far as I can tell, the program `01` gets lexed as the `0` integer literal, followed by the `1` integer literal. I suspect the intention was that `01` is an error. Or am I misreading the spec?

**Comment by alandonovan** [comment]
The spec suggests that 01 is scanned as two INT tokens, which of course is nowhere valid in the grammar, so the parser reports an error. If we consider scanning and parsing as a unit, it's a matter of implementation pragmatics that we report a specialized scanner error ("leading zero"). I'm not sure the spec needs to mandate this scanner behavior, but if we wanted to do so, it would require making the octal `o|O` optional during scanning but specifying the additional restriction on int literals that the `o|O` is is in fact mandatory for nonzero values.

**Comment by ndmitchell** [comment]
OK, that makes sense - a passing lex, but a failing parse. Of course, all implementations should probably deal with it in the lexer, or the error message ends up being a bit confused. That all makes sense.
