### ISSUE TITLE
Add list.sort

### ISSUE THREAD

**Issue by benjaminp** [bazelbuild/starlark#174]
The mutating `list.sort` method is occasionally useful for efficiency reasons.

In particular, under `--incompatible_depset_is_not_iterable`, there doesn't seem to be any way to go from a nested set to a sorted collection with less than 2 copies. One must write `sorted(a_depset.to_list())`.

**Comment by brandjon** [comment]
Also, does it make sense to talk about minimizing the number of copies if you're doing a non-in-place sort anyway? `sorted()` is [implemented](https://github.com/bazelbuild/bazel/blob/5a8a92489342d59ea74077174e29d8f10ac2989c/src/main/java/net/starlark/java/eval/MethodLibrary.java#L146) using Java's `Arrays.sort()`, which itself in the worst case behaves as merge sort (which typically is not implemented as an in-place sort).

Or to put it another way: If merge sort requires O(log n) copies, it shouldn't matter too much if we're doing O(log n) + 1 copies. Is any performance improvement demonstrable in this case?

**Comment by brandjon** [comment]
Closing as there doesn't seem to be a significant benefit here.
