### ISSUE TITLE
Does starlark support Decorators for functions

### ISSUE THREAD

**Issue by ashokponkumar** [bazelbuild/starlark#177]
Decorators for functions (https://www.python.org/dev/peps/pep-0318/) can be useful to give extra information to/about a function. 

Is it supported by Starlark now, or is there any plan to support it?

**Comment by adonovan** [comment]
No, Starlark does not support decorators, and there are no plans to add them. Decorators go against a design goal of Starlark that the code be obvious: most of its features are common to every programming language. If you come from a language that doesn't have decorators, they are quite bewildering.

No-one disputes that decorators are useful. Every feature is useful, but that's never enough.
