### ISSUE TITLE
Consider alternative implementations of list comprehension

### ISSUE THREAD

**Issue by ndmitchell** [bazelbuild/starlark#179]
In Python and Starlark as per the current spec:

```
x = [1,2]
print([x for _ in [3] for x in x])
```

Gives an error about x being an undefined variable. The reason is that _on entering_ a list comprehension, all variables are introduced in scope, so this is equivalent to:

```
x = [1,2]
print([x1 for _ in [3] for x1 in x1])
```

Whereas, according to [more formal definitions of list comprehensions](https://www.haskell.org/onlinereport/haskell2010/haskellch3.html#x8-420003.11), it would be well defined and equivalent to:

```
x = [1,2]
print([x1 for _ in [3] for x1 in x])
```

I find the Python semantics surprising. It makes no sense to shadow variables, but not consistently. It would be consistent if it overwrote x (but it doesn't). It would be consistent if each for loop introduced a new scope (but it doesn't).

[Rust Starlark](https://github.com/facebookexperimental/starlark-rust/) implements the semantics of introducing a fresh variable at each `for` expression, which gives predictable behaviour. I come from a Haskell background, which definitely biases my thoughts on this matter.

**Comment by laurentlb** [comment]
I think it's consistent with the other scopes:
- when you enter a file, all global variables are added to the scope
- when you enter a function, all local variables are added to the scope

Here, there's a new scope when you enter the list comprehension. I don't think your first example is a compelling case for changing the spec (the user should really use a different name).

Having a fresh variable at each `for` could be tempting to me, but I don't think it's consistent with the rest of the semantics (a normal for loop doesn't add a variable to the scope; it was already there).

**Comment by ndmitchell** [comment]
Hmm, I think Python should have a fresh variable at each `for` in normal loops (although appreciate that would be too big a change), and maybe my thoughts are still unable to accept that fully. I am coming around to thinking you are probably right, and that while this behaviour seems odd to me, it's consistent to other behaviour I also find odd, and consistency should probably win...

**Comment by adonovan** [comment]
I agree with Laurent: if one was starting from scratch, there are good arguments for having the scope of each variable begin at its declaration (though list comprehensions are genuinely complicated because the body appears before the `for` bindings). But that is not how Python works, or has ever worked, and whatever the benefits of that approach, they are less than the cost of doing something new and unfamiliar.

**Comment by ndmitchell** [comment]
Closing this ticket, and I'll fix Starlark Rust.
