### ISSUE TITLE
dict.update should return None, not self

### ISSUE THREAD

**Issue by alandonovan** [bazelbuild/starlark#18]
In .bzl files, the expression dict(a=1).update(b=2) evaluates to {a: 1, b: 2} but according to 
  https://github.com/bazelbuild/starlark/blob/master/spec.md#dictupdate
it should return None.

Both Pythons and Starlark-in-Go return None:

$ python # 2 or 3
>>> x = {}
>>> x.update(k=1)
>>> x
{'k': 1}

$ starlark  # in Go
>>> x = {}
>>> x.update(k=1)
>>> x
{"k": 1}

The Java standalone interpreter gives a strange error --- I have no idea what it means:
% blaze-bin/third_party/bazel/src/main/java/com/google/devtools/skylark/Skylark
>> x = {}
>> x.update(k=1)
parameter 'other' has no default value, in method call update(int k) of 'dict'

Googlers: see L23 of dart_dev_ctx.bzl in cr/223363742 for a real-world example.

**Comment by laurentlb** [comment]
Thanks!
That's a bug in Bazel.

**Comment by brandjon** [comment]
> In .bzl files, the expression dict(a=1).update(b=2) evaluates to {a: 1,
b: 2}

How does it do that? The bug is that dict.update doesn't take entries as
**kargs, so shouldn't that fail as per the example you gave?

**Comment by laurentlb** [comment]
Error message is bad, but the `.update()` method doesn't accept keyword arguments: https://docs.bazel.build/versions/master/skylark/lib/dict.html#update

If you do: `x.update({"k": 1})`, you'll see that `update()` returns None as expected.

cr/223363742 boils down to:

```python
SomeInfo = provider(
    fields = {
        "...": "...",
    }.update(other_fields),
```

This is confusing, because update returns None. In other words, the dictionary is created, modified and thrown away.

**Comment by laurentlb** [comment]
> make the Java impl and its doc match what the spec doc says

Right. Good enough, it's just a new feature and not a breaking change.

In the future, we can indeed extend the linter to catch this kind of things. Right now, we focus on the deprecated features, and help users migrate their code.

**Comment by laurentlb** [comment]
Fixed in Bazel
