### ISSUE TITLE
Consider the addition of f format strings

### ISSUE THREAD

**Issue by ndmitchell** [bazelbuild/starlark#184]
Python lets you write:

```
world = 'world'
print('Hello {}!'.format(world))
print('Hello %s!' % world)
print(f'Hello {world}!')
```

Starlark lets you write the first two, but not the third. Of these, only the third lets you put variables where they occur and thus lets you scan the string with context, instead of hopping back and forth to the end to see what gets spliced in. The recommendation for modern Python is to use f-strings (e.g. https://realpython.com/python-string-formatting/#which-string-formatting-method-should-you-use). Should we add them to Starlark? (And for bonus points, I'd love if we could remove the other two flavours, but I expect we can't.)

**Comment by illicitonion** [comment]
Strong +1 from me!

**Comment by mahmoudimus** [comment]
Dupe of https://github.com/bazelbuild/starlark/issues/91 ?

**Comment by ndmitchell** [comment]
Yep, will subscribe there.
