### ISSUE TITLE
Add removeprefix/removesuffix to string

### ISSUE THREAD

**Issue by ndmitchell** [bazelbuild/starlark#185]
Someone wanted to change `libFoos.so` to `Foos` so they did the (not unreasonable) `x.lstrip("lib").rstrip(".so")`, which looks like it does that, but completely doesn't (it returns `Foo`). I then change that to index slicing, in particular `[:-len(extension)]`, but that fails in the corner case of an empty extension. These aren't unreasonable things to do, but the default Starlark operators are full of pitfalls.

Python 3.9 added `string.removeprefix`and `string.removesuffix`. I've added them to the Rust Starlark, since they are super helpful and avoid bugs. It would be great to add them to standard Starlark too.

**Comment by adonovan** [comment]
Seems reasonable. I'm amazed they took until 3.9 to appear.

**Comment by fmeum** [comment]
@adonovan Given these are already in Rust Starlark, what would I need to do to add them to the spec + Bazel? Happy to work on PRs as I would find these functions very useful.

**Comment by adonovan** [comment]
Thanks for volunteering. Could you send a PR to change to the spec adjacent to https://github.com/bazelbuild/starlark/blob/master/spec.md#string%C2%B7endswith, which we can review? Once that's approved the maintainers of the various implementations can add the function, which should be very straightforward. I can do the Go one and @brandjon can do Java.

**Comment by fmeum** [comment]
I submitted #212 as an update to the spec and have prepared https://github.com/bazelbuild/bazel/pull/14824 to implement it in Java Starlark.
