### ISSUE TITLE
Clarify dot expressions

### ISSUE THREAD

**Issue by ndmitchell** [bazelbuild/starlark#187]
Reading https://github.com/bazelbuild/starlark/blob/master/spec.md#dot-expressions, I'm left confused. Given `x.f`. Given the context it can mean:

* `lambda *args, **kwargs: x.f(x, *args, **kwargs)`
* `x.f`

How does the code decide? Is it based on whether `f` is a function? If so, assuming a `struct` type, would selecting on function fields make it the former?

**Comment by laurentlb** [comment]
The object should know whether `f` is a field or a method.

If you store a function as a field, `x.f` will return that function. The type (in the type system) doesn't matter, there's no special case for function values.

When you access a method using `x.f`, you get a callable object that has a reference to `x`.

**Comment by ndmitchell** [comment]
Ah, I hadn't read through the spec with enough attention to method vs field. I think my brain remapped them as synonyms, when in fact they're vitally important. Thanks for the clarification!
