### ISSUE TITLE
`from "a.star" import b as b_alias` as sugar for `load("a.star", b_alias="b")` syntax

### ISSUE THREAD

**Issue by nojvek** [bazelbuild/starlark#188]
It seems the `load` function in starlark is very special. It creates name binding. As someone new to bazel this was the most confusing aspect, that load behaves like imports. The `b` argument of `load("path", "b")` specified as a string somehow ends up creating a new variable.

https://docs.bazel.build/versions/master/build-ref.html#load

The suggestion is to support `from ... import ..."` syntax.

so 

`from "//foo/bar:file.bzl" import some_library` is equivalent to `load("//foo/bar:file.bzl", "some_library")`

and 

`from ":my_rules.bzl" import some_rule, some_other_rule as nice_alias` is equivalent to `load(":my_rules.bzl", "some_rule", nice_alias = "some_other_rule")`

Pro: Increases readability and makes starlark a bit more pythonic. 
Con: Another way to do load statements.

**Comment by adonovan** [comment]
This is a subset of https://github.com/bazelbuild/starlark/issues/111. That proposal is stalled because, like yours here, it would break Python syntax compatibility.
