### ISSUE TITLE
Add dict.copy/list.copy

### ISSUE THREAD

**Issue by ndmitchell** [bazelbuild/starlark#192]
For dictionaries and lists, Python has `x.copy()` which creates a shallow copy of the dictionary/list. The way I've seen people doing this in Starlark is `dict(**original)` which is a much more complex operation both for the user, and for performance in implementation. Could these be added to Starlark?

**Comment by stepancheg** [comment]
`dict(original)` and `list(original)` work fine.

**Comment by stepancheg** [comment]
BTW, I noticed a pattern, people sometimes copy `kwargs` param not knowing that `kwargs` is a fresh dict, not shared with caller.

We may need some lint to point to this mistake.

**Comment by ndmitchell** [comment]
Thanks - excellent point! The Rust Starlark implementation also has `copy`. Do any of the other implementations? If not, it's probably best to delete these from the Rust variant.

I've also seen people cloning `kwargs` unnecessarily. It does seem a common theme.

**Comment by ndmitchell** [comment]
Thanks @stepancheg - withdrawing this suggestion, and I'll put it on my todo list to remove .copy from Rust Starlark.

**Comment by carlosgalvezp** [comment]
Hi,

This is not working, how to deep copy a dict when it contains lists inside?

```
def foo(**kwargs_in):
    kwargs = dict(kwargs_in)
    kwargs["srcs"] = ["baz.cpp"]
```

If I call "foo" 2 times, the second time will have "srcs" = ["baz.cpp"] right in the beginning of the function.
