### ISSUE TITLE
f-strings in Bazel?

### ISSUE THREAD

**Issue by daniel-v-klein** [bazelbuild/starlark#205]
Since Bazel is so Pythonesque, it'd be great if it supported the PY3 notion of f-strings https://docs.python.org/3/tutorial/inputoutput.html#fancier-output-formatting

**Comment by mahmoudimus** [comment]
dupe of https://github.com/bazelbuild/starlark/issues/91

**Comment by albertocavalcante** [comment]
@ndmitchell @laurentlb Do you have entitlement to close issues? Not sure how closing of duplicates is handled on this repo.

**Comment by ndmitchell** [comment]
I never had issue close permissions.
