### ISSUE TITLE
spec: statically reject repeated keyword arguments in call

### ISSUE THREAD

**Issue by alandonovan** [bazelbuild/starlark#21]
I notice that both Python2 and Python3 statically reject repeated keyword arguments in a call:
```
% python2 -c 'if False: f(a=1, a=1)'
  File "<string>", line 1
SyntaxError: keyword argument repeated
% python3 -c 'if False: f(a=1, a=1)'
  File "<string>", line 1
SyntaxError: keyword argument repeated
```
Perhaps Starlark should also.  Neither the Go nor Java implementation currently does.

(Note: this issue is independent of the question of whether repeated arguments are checked dynamically when a **kwargs is present in the call.)

**Comment by laurentlb** [comment]
Agree, I think we should do it.

**Comment by alandonovan** [comment]
OK, this is implemented, tested, and documented in Go.

**Comment by alandonovan** [comment]
The Java code change was https://github.com/bazelbuild/bazel/commit/9f72d7e44d27501263fb03be777babb4f14849b4
