### ISSUE TITLE
spec: should print accept keyword arguments?

### ISSUE THREAD

**Issue by alandonovan** [bazelbuild/starlark#22]
The spec https://github.com/bazelbuild/starlark/blob/master/spec.md#print says print accepts keyword arguments. This text came from the Go implementation, whose behavior it describes. The Java implementation rejects keyword arguments to print.  We should decide whether we prefer the spec as is, or the Java implementation, and make all docs and code consistent with that. Neither version of Python allows kwargs, so probably the right thing do to is disallow it.

**Comment by alandonovan** [comment]
OK, will do. Don't forget to remove the relevant sentence from spec.md in this repo.

**Comment by brandjon** [comment]
Discussed in Starlark design review meeting. We should remove **kwargs from the spec for print(), and probably add the sep= keyword arg for specifying a delimiter between *args entries. Any objections to adding sep?

**Comment by laurentlb** [comment]
`sep` is supported in Bazel. This should be easy to add it to the Go implementation as well.

**Comment by josharian** [comment]
What is outstanding here?

**Comment by laurentlb** [comment]
We just need to update the spec, remove `**kwargs`, add the `sep` argument:
  `print(*args, *, sep=" ")`

**Comment by alandonovan** [comment]
Feel free to borrow text from here:
https://github.com/google/starlark-go/blob/master/doc/spec.md#print
