### ISSUE TITLE
Debug Starlark Program Directly

### ISSUE THREAD

**Issue by wulixzCN** [bazelbuild/starlark#223]
I am using Starlark language to develop the project recently.
I wanna know can I debug the Starlark Program directly?
I read some documents like bazel, starlark debugger,etc. but no result...
Ask for help.

**Comment by ndmitchell** [comment]
There is actually a DAP debugger in the Rust Starlark code - https://github.com/facebookexperimental/starlark-rust/tree/main/starlark/bin/dap is the code, but it's hard to integrate with projects that extend Starlark. But you can debug a pure-Starlark program.

**Comment by brandjon** [comment]
Debugging is a feature of a Starlark implementation. I don't believe there's anything specific that needs to be said about it in the language spec.
