### ISSUE TITLE
Keyword-only arguments

### ISSUE THREAD

**Issue by laurentlb** [bazelbuild/starlark#23]
Keyword-only arguments are described in a Python PEP: https://www.python.org/dev/peps/pep-3102/

Examples:

```python
def compare(a, b, *, key=None): ...

def sortwords(*wordlist, case_sensitive=False): ...
```

It is supported in the Java implementation. There was a desire to remove this feature, to keep Starlark a subset of Python 2 and Python 3 syntax. However, this feature is useful and often requested:
 * Many builtins use it
 * Documentation in Bazel uses that syntax
 * Macros in Bazel shouldn't allow positional arguments, for maintenance reasons

This doesn't conflict with https://github.com/bazelbuild/starlark/issues/13#issuecomment-433995990, because #13 concerns only the call sites. The current issue concerns only the definition sites.

**Comment by alandonovan** [comment]
I'm not averse to it; the ability to require named arguments at call sites does improve maintainability.

I have an implementation for Starlark-go in https://github.com/google/starlark-go/pull/62.

**Comment by laurentlb** [comment]
Let's add keyword-only arguments to the specification.

**Comment by adonovan** [comment]
Sounds good to me. I'll dust off that implementation.

**Comment by jmillikin** [comment]
Can we also have support for required keyword-only parameters? Currently required parameters must be positional, which makes it easy for calling code to accidentally forget to use kwarg style. Python 3 supports the notion of "this parameter is required, and must be named".

```python
def foo(ctx, *, source, options = []):
  print("source: {}, options: {}".format(source, options))
```
```
>>> foo(ctx)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: foo() missing 1 required keyword-only argument: 'source'

>>> foo(ctx, ctx.file.src)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: foo() takes 1 positional argument but 2 were given

>>> foo(ctx, source = ctx.file.src)
source: <generated file>, options: []
>>> 
```

**Comment by adonovan** [comment]
Yes, we can we also have support for required keyword-only parameters. It's a nice feature and it's not hard to implement. It's already done in Starlark-in-Java,  and I just mailed out a CL for it in Go.

**Comment by laurentlb** [comment]
It's disabled in Starlark-in-Java at the moment (for no good reason), but I can re-enable it.

**Comment by alandonovan** [comment]
https://github.com/google/starlark-go/pull/151 added this feature to the Go implementation and its documentation.

**Comment by mehrdadn** [comment]
Hi, does Starlark support keyword-only arguments that aren't optional?
For optional keyword-only arguments Bazel seems to work fine, but for required ones I get `Keyword-only argument is forbidden.`

**Comment by jmillikin** [comment]
> It's disabled in Starlark-in-Java at the moment (for no good reason), but I can re-enable it.

I've filed https://github.com/bazelbuild/bazel/issues/10416 to request re-enabling mandatory keyword parameters in Java Starlark.

**Comment by phst** [comment]
Since https://github.com/bazelbuild/bazel/issues/10416 is now fixed, could this please be documented in the spec?
