### ISSUE TITLE
Support `toml` marshall/unmarshall 

### ISSUE THREAD

**Issue by aignas** [bazelbuild/starlark#254]
For the same reasons that #219. Python and Rust use `toml` as the format to store metadata and having native implementation to encode and decode such files could potentially lead to easier implementation of `bzlmod` extensions and/or repository rules, where we would need to read a `Cargo.toml` or `pyproject.toml` or a `poetry` or `pdm` lockfile to construct valid bazel targets.

**Comment by stepancheg** [comment]
This is the repo about starlark specification, not one of several starlark implementations.

I think TOML does not belong to the common starlark spec.
