### ISSUE TITLE
inconsistent acceptance of trailing commas in argument lists

### ISSUE THREAD

**Issue by alandonovan** [bazelbuild/starlark#26]
Copying @josharian's post at https://github.com/google/starlark-go/issues/83:

```
$ starlark
Welcome to Starlark (go.starlark.net)
>>> def f(*args, **kwargs): pass
... 
>>> f(1,)
>>> f(*(1,2),)
... 
<stdin>:1:11: got ')', want argument
>>> f(a=1,)
>>> f(**{"a": 1},)
... 
<stdin>:1:15: got ')', want argument
>>>  
```

Observe that for plain positional and keyword args, a trailing comma is accepted. The other two cases are not.

Python 2 behaves the same as starlark-go; Python 3 accepts all forms.

I prefer the Python 3 behavior.

```
$ python2
Python 2.7.15 (default, Jun 17 2018, 12:46:58) 
>>> def f(*args, **kwargs): pass
... 
>>> f(1,)
>>> f(*(1,2),)
  File "<stdin>", line 1
    f(*(1,2),)
             ^
SyntaxError: invalid syntax
>>> f(a=1,)
>>> f(**{"a": 1},)
  File "<stdin>", line 1
    f(**{"a": 1},)
                ^
SyntaxError: invalid syntax
```

```
$ python3
Python 3.7.1 (default, Nov 14 2018, 12:09:13) 
>>> def f(*args, **kwargs): pass
... 
>>> f(1,)
>>> f(*(1,2),)
>>> f(a=1,)
>>> f(**{"a": 1},)
```

I haven't checked yet what the spec mandates.

**Comment by laurentlb** [comment]
This was intended. Starlark-Java has the same (weird) behavior as Starlark-Go and Python 2.

Discussion from dropping Python 2 syntax compatibility: https://github.com/bazelbuild/starlark/issues/27

**Comment by jmillikin-stripe** [comment]
I stub my toe on this issue every couple days. Now that Starlark has definitively dropped Python 2 syntax compatibility, can the spec be amended to allow trailing commas?

**Comment by laurentlb** [comment]
Sounds good to me - cc @Quarz0  

fyi, Buildifier should fix the commas for you. I suspect most users don't notice the issue.

**Comment by alandonovan** [comment]
The spec permits a comma after every argument (in a call) and parameter (in a def statement), no matter which form, even the last one. The Java and Go implementations agree.
