### ISSUE TITLE
Drop Python 2 syntax compatibility

### ISSUE THREAD

**Issue by laurentlb** [bazelbuild/starlark#27]
Starlark syntax was designed as a subset of both Python 2.7 and Python 3.

Why?
Historically, Google used Python 2 for evaluating Bazel files. Starlark was designed such that Google could  migrate the files from Python 2 to Starlark. Starlark had to remain a subset of Python 2, so that other tools could continue handling the files.

Things have changed in the last few years. Most tools now use a proper Starlark parser. There are still Python-based tools, but most of the world is moving (or has moved) to Python 3... even inside Google.

Reasons to drop the Python 2 compatibility include:
 - https://github.com/bazelbuild/starlark/issues/23
 - https://github.com/bazelbuild/starlark/issues/26

I suggest we drop the Python 2 syntax compatibility.
Any objection?

**Comment by alandonovan** [comment]
No objection from me.

**Comment by brandjon** [comment]
Sounds exciting.

**Comment by simeg** [comment]
What is the status for this? I see the "approved" label but I can't tell if enough changes has been made.

**Comment by laurentlb** [comment]
Syntax compatibility with Python 2 is no longer guaranteed.
We can discuss specific cases in other issues (see links from the first message).

**Comment by simeg** [comment]
Does this mean that Starlark is not dependent on Python 2?

**Comment by laurentlb** [comment]
Starlark is a separate language, it's not dependent on Python.

We try to keep the syntax compatible with Python 3 (and no longer Python 2). This was useful at the beginning as we could reuse some Python tooling; nowadays, it's getting less important as we build tools specifically for Starlark.

**Comment by albertocavalcante** [comment]
> Syntax compatibility with Python 2 is no longer guaranteed.
> We can discuss specific cases in other issues (see links from the first message).

@laurentlb Just wondering — is there a documentation link that also mentions it? Also, should this issue remain open, or can be closed in that case?

**Comment by laurentlb** [comment]
I think this one can be closed.
I don't see any action item (do you think there's any documentation to update?).
