### ISSUE TITLE
"Awesome Starlark"

### ISSUE THREAD

**Issue by dbohdan** [bazelbuild/starlark#288]
It could help promote the language and projects that implement, extend, and use it if `users.md` were transformed into an official ["awesome list"](https://github.com/sindresorhus/awesome) repository. A link in sindresorhus/awesome would introduce users from outside the Bazel community to Starlark.

**Comment by laurentlb** [comment]
Interesting idea. users.md doesn't fit very well with the rest of the repository and it can be hard to get maintainers' attention for the small PRs.

I have created https://github.com/laurentlb/awesome-starlark and we can iterate for there.

**Comment by dbohdan** [comment]
Excellent!

**Comment by dbohdan** [comment]
I think it would make sense to replace the contents of `users.md` with a link to Awesome Starlark in order to have a single source of truth.
