### ISSUE TITLE
Why was Skylark renamed to Starlark?

### ISSUE THREAD

**Issue by kastiglione** [bazelbuild/starlark#3]
Just curious

**Comment by kastiglione** [comment]
I see it's answered here: https://blog.bazel.build/2018/08/17/starlark.html

**Comment by jxramos** [comment]
Interesting, I think I didn't even notice until it was brought up in the [Bazel with Tony Aiuto
podcast](https://www.gcppodcast.com/post/episode-153-bazel-with-tony-aiuto/) at 16:35

The trademark conflict I'm guessing must be with this company...
https://www.swiftnav.com/news/swift-​​navigation-​​introduces-skylark-cloud-based-high-precision-gnss-service

Good to know.

**Comment by jkugler** [comment]
All it says is:
> At the same time, its very name must also change for trademark reasons.

What trademark? Whose trademark? Who asserted trademark infringement?

**Comment by laurentlb** [comment]
Google trademark team recommended us to use a different name before we use it more widely (e.g. before getting a domain name or the GitHub repository).

There has been no complaint.
