### ISSUE TITLE
Spec is unclear on / operator

### ISSUE THREAD

**Issue by illicitonion** [bazelbuild/starlark#31]
The spec states that `/` is a binary operator (a `Binop`), but doesn't give it any meaning (it's not considered an Arithmetic operation.

It is included as an Augmented assignment (`/=`), but without behavioural specification.

These all appear in the grammar reference.

Should `/` be removed from the grammar, or should its behaviour be specified?

**Comment by laurentlb** [comment]
As in Python 3, `//` should be integer division and `/` should be float division. However, the spec doesn't define floats at the moment.

Starlark-Go implementation can support floats behind a flag. If you don't support floats, you should raise an error for the `/` operator.

Keeping it in the grammar can help tools (e.g. formatter, linter) handle it.

**Comment by alandonovan** [comment]
This is addressed by https://github.com/bazelbuild/starlark/pull/119, which should hopefully be committed later today.
