### ISSUE TITLE
add -c flag

### ISSUE THREAD

**Issue by josharian** [bazelbuild/starlark#35]
Feature request: add a -c flag to pass a program to evaluate on the command line. This facilitates fuzzing and quick demos.

Go: https://github.com/google/starlark-go/pull/47
Rust: https://github.com/google/starlark-rust/issues/36

Thanks!

**Comment by laurentlb** [comment]
To clarify, this issue is for Starlark-in-java (instructions to use are here: https://github.com/bazelbuild/starlark/issues/24).

**Comment by laurentlb** [comment]
Implemented
