### ISSUE TITLE
spec: built-in 'dir' function should return a sorted list

### ISSUE THREAD

**Issue by alandonovan** [bazelbuild/starlark#40]
The Python spec for the `dir` built-in function https://docs.python.org/2/library/functions.html#dir says "the resulting list is sorted alphabetically". Neither the Java nor Go implementations match this behavior. I think the spec and both implementations should be changed to match Python. Given that the current order is unspecified, and given typical uses of the dir function, this should be a safe change.

**Comment by josharian** [comment]
Yes please. See also: https://github.com/google/starlark-rust/issues/64

**Comment by laurentlb** [comment]
In the Java implementation, the output of `dir` has always been sorted (https://github.com/bazelbuild/bazel/blob/973c4e7406a7d397f796414cdbc54dd7e082b68d/src/main/java/com/google/devtools/build/lib/syntax/MethodLibrary.java#L743).

**Comment by alandonovan** [comment]
So it has! Not sure how I missed that. Too much time in Go perhaps, which has no sorted sets.

**Comment by alandonovan** [comment]
The Go and Java implementations of `dir` both sort, and the Go docs specify it. This PR updates the spec:
 https://github.com/adonovan/starlark/pull/new/sorted-dir
