### ISSUE TITLE
how to get the maxint

### ISSUE THREAD

**Issue by HuKeping** [bazelbuild/starlark#43]
is there anyway to get the maximum/minimum value?

**Comment by laurentlb** [comment]
No.
Some implementations (e.g. the one in Go) have no maximum value, ints are unbounded.
In the Java implementation, there's a maximum value, but it shouldn't be meaningful.

Why do you need this?

**Comment by HuKeping** [comment]
@laurentlb I found it might useful when I fix a bug in bazelbuild/rules_foreign_cc 

https://github.com/bazelbuild/rules_foreign_cc/pull/259

**Comment by laurentlb** [comment]
Workaround is quite simple:

```python
level = None
...
if level == None or level > file_level:
  level = file_level
```
