### ISSUE TITLE
Add a built-in function similar to fail/assert

### ISSUE THREAD

**Issue by Quarz0** [bazelbuild/starlark#47]
**Related:** https://github.com/google/starlark-go/pull/208#pullrequestreview-241974184

The Go implementation currently lacks a function similar to [fail()](https://docs.bazel.build/versions/master/skylark/lib/globals.html#fail) which is implemented in both Starlark Java and Rust. fail() is also used in both their test runners ([java](https://github.com/bazelbuild/bazel/blob/master/src/test/starlark/starlark_test.py#L81), [rust](https://github.com/google/starlark-rust/blob/master/starlark/tests/testutil/mod.rs#L87)) as they define assertion functions in every test and use it to throw errors when those assertions fail.

Go on the other hand uses a built-in [assert module](https://github.com/google/starlark-go/blob/master/starlarktest/assert.star) for test cases which include assert.eq(), assert.fails() and similar.
I think that a function similar to fail, or a more general one such as assert function/keyword would be useful to remove these inconsistencies. A function similar to assert for example could be used in the test cases of all 3 implementations and do the job of fail().

**Comment by laurentlb** [comment]
I agree we should add a fail function.

My suggestion is to have just one argument, of any type. Like for print, the host application decides how the message is reported to the user.

In Bazel, we have a second argument (`attr`), but it's not very useful. I'd rather get rid of it.

(cc @alandonovan)

**Comment by alandonovan** [comment]
I agree we should get rid of attr. 

If `fail` accepts one argument of any type, this raises the question of what the type signifies: if the argument is merely turned into a string somehow, then `fail` should specify how that conversion occurs, just as `print` specifies the string conversion but not what happens to the resulting string; if instead the argument is not stringified but its type and value are preserved, this raises the question of how the host application can access the fail value, which implies an exception mechanism. I don't want to go there.

I suggest we specify fail as follows:
---
The fail(*args, sep=" ") function causes execution to fail with the specified error message. Like `print`, each argument x is formatted as if by str(x) and separated by a space, unless an alternative separator is specified by the `sep` argument.
---




BTW, the documentation for the print built-in at google/starlark-go and at bazelbuild/starlark are both incorrect. The correct text and examples should be:

```
print(*args, sep=" ") prints its arguments, followed by a newline. Each argument x is formatted as if by str(x) and separated with a space, unless an alternative separator is specified by the sep argument.

Example:
print(1, "hi")		       		# "1 hi\n"
print("hello", "world")			# "hello world\n"
print("hello", "world", sep=", ")	# "hello, world\n"

Typically the formatted string is printed to the standard error file, but the exact behavior is a property of the Starlark thread and is determined by the host application.
```

**Comment by laurentlb** [comment]
Sounds good to me.
Using the same as `print` seems useful and consistent.

**Comment by brandjon** [comment]
Maybe the spec says otherwise, but `print()` doesn't format as if by `str()` in the java implementation, it uses the separate debug representation which may include information that is unsafe for reflection into starlark (e.g. non-deterministic information).

**Comment by alandonovan** [comment]
This change requires removal of the attr=... parameter from the Java implementation, which requires a clean-up (100 uses in Google's code base, more in Bazel).

**Comment by alandonovan** [comment]
Fail is now specified, and implemented in Go and Java. Closing.
