### ISSUE TITLE
Add "generator_function_location" attribute

### ISSUE THREAD

**Issue by murali42** [bazelbuild/starlark#5]
Terminology:
  generator = rule or macro.

Request:
Add a "generator_function_location" attribute would contain the path of the .bzl file which defined the generator which generated the current rule. Line number is not really needed.

Justification:
The location of the .bzl file containing the generator together with the name of the generator results in a fully qualified name. If the generator_function_location attribute was added, it is possible to figure out that two rule instances were actually generated by different generators.

Eg.

foo/one.bzl: defines a rule "abc"
foo/two.bzl: defines a rule "abc"
foo/both.bzl: 
  load("//foo:x.bzl", one_abc = "abc")
  load("//foo:y.bzl", two_abc = "abc")

bar/BUILD
  load("//foo:both.bzl", "one_abc", "two_abc")
  load("//foo:one.bzl", "abc")
  abc(name="p", ...)
  one_abc(name="q", ...)
  two_abc(name="r", ...)

Without a generator_function_location it is not possible to know that the rules "p" and "q" were generated by the same rule, but "r" was not. Currently all three rules will have generator_function = "abc".

**Comment by murali42** [comment]
In case it helps. The generator_function_location only needs to include the path to the .bzl file. The line number is not needed. That should help with reducing memory usage and make interning more effective.

**Comment by laurentlb** [comment]
I wonder if this information should really be part of the build tool (and available through e.g. `bazel query`), or if it can be exposed by a separate tool.

**Comment by murali42** [comment]
If it is not available via `bazel query` then the separate tool would need to reimplement skylark logic. Since this is a synthetic attribute couldn't we make it so it doesn't use any memory at all, but computed when asked via `bazel query`?

**Comment by laurentlb** [comment]
In Bazel, that seems complicated to implement (`bazel query` will not reread source files).

A separate tool can embed a Starlark interpreter. @c-parsons has done that for a documentation generator prototype.

**Comment by murali42** [comment]
Separate tool will not be performant enough right?

`bazel query <some expression>`

and now the tool would need to be passed in the same set of rules returned by the query, and the tool would need to parse the same files all over again. Also in my specific use case, the files themselves are remote, so the tool doesn't even have access to the files.

**Comment by alandonovan** [comment]
Marking as obsolete. Blaze query now reports the complete instantiation stack of a rule. (Also this issue is about a Bazelism, not a core Starlark concept.)
