### ISSUE TITLE
spec: no mention of optional parameters start, end in string.startswith/endswith

### ISSUE THREAD

**Issue by Quarz0** [bazelbuild/starlark#56]
The [go-spec](https://github.com/google/starlark-go/blob/master/doc/spec.md#stringstartswith) does mention the start, end arguments. And both the Java and Go implementations support these optional arguments. Only the rust implementation is different where it only accepts the parameter suffix, which must be a string.

**Comment by laurentlb** [comment]
We should update the spec (to match the Java/Go implementations).
