### ISSUE TITLE
spec: no mention of optional argument 'cutset' of strip

### ISSUE THREAD

**Issue by Quarz0** [bazelbuild/starlark#60]
The go and java implementations `strip`/`rstrip`/`lstrip` functions accept a cutset optional parameter however it is missing from the [spec](https://github.com/bazelbuild/starlark/blob/master/spec.md#stringstrip). It is mentioned however in the [go-spec](https://github.com/google/starlark-go/blob/master/doc/spec.md#stringstrip).

The Rust implementation, on the other hand, does not support the cutset argument.

**Comment by laurentlb** [comment]
Thanks, we need to update the spec.
