### ISSUE TITLE
Link to specification markdown is broken.

### ISSUE THREAD

**Issue by take-cheeze** [bazelbuild/starlark#7]
(I don't know where to report but it should relate here.)
In https://docs.bazel.build/versions/master/skylark/language.html `Starlark Language Specification` link should link to https://github.com/bazelbuild/starlark/blob/master/spec.md but it links to https://github.com/bazelbuild/starlark/blob/master/spec.html .

**Comment by laurentlb** [comment]
Thanks, it's fixed now.
