### ISSUE TITLE
Request for feedback: Indented template/render literals

### ISSUE THREAD

**Issue by andrewchambers** [bazelbuild/starlark#72]
For my own purposes I require some sort of improved version of python fstrings, consider the following:

# Render literal
```
def some_template(a):
  return ``
    <html>
      <p>echo `{a}</p>
    <html>
  ``

def another_template(cfile):
  return ``
    #! /bin/sh
    cc -c "`{cfile}"
  ``
```
## sugar for
```
def some_template(a):
  return ["<html>\n  <p>echo ", a, "</p>\n<html>"]

def another_template(a):
  return [""#! /bin/sh\ncc -c \"", cfile, "\"\n"]
```
# Postfix Render operators
```
html_escape ``
    <html>
      <p>echo `{a+"<script>..."}</p>
    <html>
  ``
```
## sugar for
```
html_escape(["<html>\n  <p>echo ", a+"<script>...", "  </p>\n<html>"])
```

The key features being embedding of expressions and taking indentation of the code into account so code can be formatted nicely.

I personally think this would be extremely useful for generation of many types of text, especially code, and replace many uses of string % or format where the number of arguments grows.

The utility is also improved as you are not required to render to string (another one of my requirements).

So my questions are:

Is starlark willing to break with python for things like this? What are peoples general feedback or thoughts on the idea?

Thanks for reading

**Comment by andrewchambers** [comment]
I have implemented this feature in my own fork.

**Comment by alandonovan** [comment]
> Is starlark willing to break with python for things like this?

Very unlikely. You can get 90% of the benefit without changing the language, by calling suitably-defined library functions:

```
def some_template(a):
  return parse(```
    <html>
      <p>echo {{.a}}</p>
    <html>
  ```)

def another_template(cfile):
  return parse(```
    #! /bin/sh
    cc -c "{{.cfile}}"
  ```)
```

**Comment by andrewchambers** [comment]
@alandonovan 

If you are suggesting to implement it as a builtin, the debug api implementation I am using (go) seems insufficient to implement capturing runtime values, but other than that it is a good point.

**Comment by alandonovan** [comment]
My example was intended to illustrate a parser that turns a string literal into some form that can be "applied" to an appropriate set of values (a map, say). The corresponding apply function would take the parsed form and the map and yield the template expansion as a string, similar to the Parse and Execute functions in Go's template package.

Unlike Python, Starlark has no operator like `globals` or `locals` that materializes the current environment as a map, so you would have to supply the argument values explicitly.

It might be useful to allow general Starlark expressions inside the `{{...}}` holes in the template, not just variables, but that would require substantially more design. As a first step I suggest supporting only a few limited forms, including function calls, and requiring users to pass the necessary functions in as arguments. If you aren't already familiar with Go's template mechanism, it has a lot of nice ideas from which to take inspiration: https://golang.org/pkg/text/template/

**Comment by andrewchambers** [comment]
Ah I see... WIP fwiw my implementation is here:

https://github.com/andrewchambers/starlark-go/commit/a86d2c2fcde639eb6314ffa01b2ae10d72673a2f

I supported all starlark expressions and nesting of render literals, it was a bit tricky but possible using some trick in the scanner.
