### ISSUE TITLE
default argument of getattr

### ISSUE THREAD

**Issue by laurentlb** [bazelbuild/starlark#73]
`getattr` function has a third optional argument (a default value). This is supported by the Java and the Go version, but it's missing in the specification.

https://github.com/bazelbuild/starlark/blob/master/spec.md#getattr
https://docs.bazel.build/versions/master/skylark/lib/globals.html#getattr

We should document it.
cc @Quarz0

**Comment by alandonovan** [comment]
Done. https://github.com/google/starlark-go/commit/52794b6d230111cdb5f3f45816f441da67c09926

**Comment by alandonovan** [comment]
This is done. It is document in the spec and the Go implementation (different words but same behavior), and implemented in Go and Java.
