### ISSUE TITLE
Starlark mailing list is private or missing

### ISSUE THREAD

**Issue by eaceaser** [bazelbuild/starlark#74]
The mailing list linked to [here](https://github.com/bazelbuild/starlark/blob/master/README.md#evolution):  https://groups.google.com/forum/#!forum/starlark is either missing or private. If it isn't the active discussion forum for the project, can it be updated with something that is?

**Comment by laurentlb** [comment]
I don't know what happened, but it should be fixed. You should be able to read/join.

Most discussions happen on GitHub though.

**Comment by jmillikin-stripe** [comment]
@laurentlb can you verify that the list is public, for example by opening it in an incognito window? I am also unable to view it.

**Comment by jin** [comment]
I'm also unable to access the mailing list.

**Comment by joeflack4** [comment]
Same here. Looks like this should be re-opened, but hasn't yet. So I'll create a new issue.
