### ISSUE TITLE
Commented out test in Go's `assign.star`

### ISSUE THREAD

**Issue by finn-ball** [bazelbuild/starlark#96]
Is there a reason this test was commented out?

https://github.com/bazelbuild/starlark/blob/master/test_suite/testdata/go/assign.star#L258-L273

**Comment by alandonovan** [comment]
Yes: the Java implementation of Starlark doesn't allow field assignment x.f=y. I don't think it's even accepted by the parser.

**Comment by alandonovan** [comment]
I should add: but I would accept a PR to add support for it in the parser, and a StarlarkValue subinterface that allows an object x to define the behavior of x.f=y.

**Comment by alandonovan** [comment]
Support for x.f=y assignments was added to the Java implementation in: https://github.com/bazelbuild/bazel/commit/a8f007500f8930934524b379befec0d93d762fde
